"undefined"===typeof window.ulb&&(window.ulb={});
(function(r,k,d){var p=d(r),u=d(k),a=d.fancybox=function(){a.open.apply(this,arguments)},v=!1,t="undefined"!==typeof k.createTouch,n;d.extend(a,{version:"2.0.5",defaults:{padding:15,margin:20,width:800,height:600,minWidth:100,minHeight:100,maxWidth:9999,maxHeight:9999,autoSize:!0,autoResize:!t,autoCenter:!t,fitToView:!0,aspectRatio:!1,topRatio:.5,fixed:!(d.browser.msie&&6>=d.browser.version)&&!t,scrolling:"auto",wrapCSS:"fancybox-default",arrows:!0,closeBtn:!0,closeClick:!1,nextClick:!1,mouseWheel:!0,
autoPlay:!1,playSpeed:3E3,preload:3,modal:!1,loop:!0,ajax:{dataType:"html",headers:{"X-fancyBox":!0}},keys:{next:[13,32,34,39,40],prev:[8,33,37,38],close:[27]},tpl:{wrap:'<div class="fancybox-wrap"><div class="fancybox-outer"><div class="fancybox-inner"></div></div></div>',image:'<img class="fancybox-image" src="{href}" alt="" />',iframe:'<iframe class="fancybox-iframe" name="fancybox-frame{rnd}" frameborder="0" hspace="0"'+(d.browser.msie?' allowtransparency="true"':"")+"></iframe>",swf:'<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%"><param name="wmode" value="transparent" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="{href}" /><embed src="{href}" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="100%" height="100%" wmode="transparent"></embed></object>',
error:'<p class="fancybox-error">'+ulb.error+"</p>",closeBtn:'<div title="'+ulb.closeBtn+'" class="fancybox-item fancybox-close"></div>',next:'<a title="'+ulb.next+'" href="javascript://" class="fancybox-nav fancybox-next"><span></span></a>',prev:'<a title="'+ulb.prev+'" href="javascript://" class="fancybox-nav fancybox-prev"><span></span></a>'},openEffect:"fade",openSpeed:250,openEasing:"swing",openOpacity:!0,openMethod:"zoomIn",closeEffect:"fade",closeSpeed:250,closeEasing:"swing",closeOpacity:!0,
closeMethod:"zoomOut",nextEffect:"elastic",nextSpeed:300,nextEasing:"swing",nextMethod:"changeIn",prevEffect:"elastic",prevSpeed:300,prevEasing:"swing",prevMethod:"changeOut",helpers:{overlay:{speedIn:0,speedOut:300,opacity:.8,css:{cursor:"pointer"},closeClick:!0},title:{type:"float"}}},group:{},opts:{},coming:null,current:null,isOpen:!1,isOpened:!1,wrap:null,outer:null,inner:null,player:{timer:null,isActive:!1},ajaxLoad:null,imgPreload:null,transitions:{},helpers:{},open:function(b,c){a.close(!0);
b&&!d.isArray(b)&&(b=b instanceof d?d(b).get():[b]);a.isActive=!0;a.opts=d.extend(!0,{},a.defaults,c);d.isPlainObject(c)&&"undefined"!==typeof c.keys&&(a.opts.keys=c.keys?d.extend({},a.defaults.keys,c.keys):!1);a.group=b;a._start(a.opts.index||0)},cancel:function(){a.coming&&!1===a.trigger("onCancel")||(a.coming=null,a.hideLoading(),a.ajaxLoad&&a.ajaxLoad.abort(),a.ajaxLoad=null,a.imgPreload&&(a.imgPreload.onload=a.imgPreload.onabort=a.imgPreload.onerror=null))},close:function(b){a.cancel();a.current&&
!1!==a.trigger("beforeClose")&&(a.unbindEvents(),!a.isOpen||b&&!0===b[0]?(d(".fancybox-wrap").stop().trigger("onReset").remove(),a._afterZoomOut()):(a.isOpen=a.isOpened=!1,d(".fancybox-item, .fancybox-nav").remove(),a.wrap.stop(!0).removeClass("fancybox-opened"),a.inner.css("overflow","hidden"),a.transitions[a.current.closeMethod]()))},play:function(b){var c=function(){clearTimeout(a.player.timer)},e=function(){c();a.current&&a.player.isActive&&(a.player.timer=setTimeout(a.next,a.current.playSpeed))},
f=function(){c();d("body").unbind(".player");a.player.isActive=!1;a.trigger("onPlayEnd")};a.player.isActive||b&&!1===b[0]?f():a.current&&(a.current.loop||a.current.index<a.group.length-1)&&(a.player.isActive=!0,d("body").bind({"afterShow.player onUpdate.player":e,"onCancel.player beforeClose.player":f,"beforeLoad.player":c}),e(),a.trigger("onPlayStart"))},next:function(){"undefined"==typeof getPhotoVars||n||(n=getPhotoVars());if(n&&a.current)for(var b=a.current.index=0;b<a.group.length;b++){m1=a.group[b].href.match(/\/\d+\.[^\?]+/i);
m2=a.current.href.match(/\/\d+\.[^\?]+/i);if(m1[0]==m2[0])break;a.current.index++}a.current&&a.jumpto(+a.current.index+1,1);console.log(a.current)},prev:function(){"undefined"==typeof getPhotoVars||n||(n=getPhotoVars());if(n&&a.current)for(var b=a.current.index=0;b<a.group.length;b++){m1=a.group[b].href.match(/\/\d+\.[^\?]+/i);m2=a.current.href.match(/\/\d+\.[^\?]+/i);if(m1[0]==m2[0])break;a.current.index++}a.current&&a.jumpto(+a.current.index-1,-1)},jumpto:function(b,c){"undefined"==typeof getPhotoVars||
n||(n=getPhotoVars());if(n){var e=a.current.href.split("?");if(t=checkPhotoPosition(n.photoUrls,e[0])){var d,g=pages=0;$.each(n.photoUrls,function(a){for(var b in a)g++;pages++});1==t[0]?d=res="undefined"==typeof n.photoUrls[parseInt(t[1])+1]?1:parseInt(t[1])+1:-1==t[0]&&(d=res=1>t[1]-1?Math.max.apply(Math,Object.keys(n.photoUrls)):parseInt(t[1])-1);if(1!=pages&&(null==n.photoUrls[d]||g!=a.group.length)){var q=function(){var e=$(a.group[0]).clone()[0];a.group=[];i=0;$.each(n.photoUrls,function(d,
f){f&&$.each(f,function(d,f){var g=$(e).clone()[0];$(g).attr("data-url","/photo/0-0-"+f[0]);g.href=f[1];a.group.push(g);a.current.href==g.href&&(b=h=i+c);i++})});a.current&&(h=parseInt(h,10),1<a.group.length&&a.current.loop&&(h>=a.group.length?h=0:0>h&&(h=a.group.length-1)),"undefined"!==typeof a.group[h]&&(a.cancel(),a._start(h)))};url=n.pageUrlMask.replace(/\%[pa]/gi,function(a){if("%p"==a)return d;if("%a"==a)return 1});var h=b;n.photoUrls[d]?q():$.ajax({url:url,success:function(a){n.photoUrls[d]=
a;q()}});return}}}a.current&&(b=parseInt(b,10),1<a.group.length&&a.current.loop&&(b>=a.group.length?b=0:0>b&&(b=a.group.length-1)),"undefined"!==typeof a.group[b]&&(a.cancel(),a._start(b)))},reposition:function(b){a.isOpen&&a.wrap.css(a._getPosition(b))},update:function(b){a.isOpen&&(v||setTimeout(function(){var c=a.current;if(v&&(v=!1,c)){if(c.autoResize||b&&"orientationchange"===b.type)c.autoSize&&(a.inner.height("auto"),c.height=a.inner.height()),a._setDimension(),c.canGrow&&a.inner.height("auto");
c.autoCenter&&a.reposition();a.trigger("onUpdate")}},100),v=!0)},toggle:function(){a.isOpen&&(a.current.fitToView=!a.current.fitToView,a.update())},hideLoading:function(){d("#fancybox-loading").remove()},showLoading:function(){a.hideLoading();d('<div id="fancybox-loading"><div></div></div>').click(a.cancel).appendTo("body")},getViewport:function(){return{x:p.scrollLeft(),y:p.scrollTop(),w:p.width(),h:window.innerHeight}},unbindEvents:function(){a.wrap&&a.wrap.unbind(".fb");u.unbind(".fb");p.unbind(".fb")},
bindEvents:function(){var b=a.current,c=b.keys;b&&(p.bind("resize.fb, orientationchange.fb",a.update),c&&u.bind("keydown.fb",function(b){var f;!(b.ctrlKey||b.altKey||b.shiftKey||b.metaKey)&&0>d.inArray(b.target.tagName.toLowerCase(),["input","textarea","select","button"])&&(f=b.keyCode,-1<d.inArray(f,c.close)?(a.close(),b.preventDefault()):-1<d.inArray(f,c.next)?(a.next(),b.preventDefault()):-1<d.inArray(f,c.prev)&&(a.prev(),b.preventDefault()))}),d.fn.mousewheel&&b.mouseWheel&&1<a.group.length&&
a.wrap.bind("mousewheel.fb",function(b,c){var g=d(b.target).get(0);if(0===g.clientHeight||g.scrollHeight===g.clientHeight&&g.scrollWidth===g.clientWidth)b.preventDefault(),a[0<c?"prev":"next"]()}))},trigger:function(b){var c,e=a[-1<d.inArray(b,["onCancel","beforeLoad","afterLoad"])?"coming":"current"];if(e){d.isFunction(e[b])&&(c=e[b].apply(e,Array.prototype.slice.call(arguments,1)));if(!1===c)return!1;e.helpers&&d.each(e.helpers,function(c,g){if(g&&"undefined"!==typeof a.helpers[c]&&d.isFunction(a.helpers[c][b]))a.helpers[c][b](g,
e)});d.event.trigger(b+".fb")}},isImage:function(a){return a&&(a.match(/\.(jpg|gif|png|bmp|jpeg)(.*)?$/i)||a.match(/^data:image\/(jpg|gif|png|bmp|jpeg);base64,/i))},isSWF:function(a){return a&&a.match(/\.(swf)(.*)?$/i)},_start:function(b){var c={},e=a.group[b]||null,f,g,q;e&&(e.nodeType||e instanceof d)&&(f=!0,d.metadata&&(c=d(e).metadata()));c=d.extend(!0,{},a.opts,{index:b,element:e},d.isPlainObject(e)?e:c);d.each(["href","title","content","type"],function(b,g){c[g]=a.opts[g]||f&&d(e).attr(g)||c[g]||null});"number"===typeof c.margin&&(c.margin=[c.margin,
c.margin,c.margin,c.margin]);c.modal&&d.extend(!0,c,{closeBtn:!1,closeClick:!1,nextClick:!1,arrows:!1,mouseWheel:!1,keys:null,helpers:{overlay:{css:{cursor:"auto"},closeClick:!1}}});a.coming=c;!1===a.trigger("beforeLoad")?a.coming=null:(g=c.type,b=c.href||e,g||(f&&(q=d(e).data("fancybox-type"),!q&&e.className&&(g=(q=e.className.match(/fancybox\.(\w+)/))?q[1]:null)),!g&&"string"===d.type(b)&&(a.isImage(b)?g="image":a.isSWF(b)?g="swf":b.match(/^#/)&&(g="inline")),g||(g=f?"inline":"html"),c.type=g),
"inline"===g||"html"===g?(c.content||(c.content="inline"===g?d("string"===d.type(b)?b.replace(/.*(?=#[^\s]+$)/,""):b):e),c.content&&c.content.length)||(g=null):b||(g=null),c.group=a.group,c.isDom=f,c.href=b,"image"===g?a._loadImage():"ajax"===g?a._loadAjax():g?a._afterLoad():a._error("type"))},_error:function(b){a.hideLoading();d.extend(a.coming,{type:"html",autoSize:!0,minHeight:0,hasError:b,content:a.coming.tpl.error});a._afterLoad()},_loadImage:function(){a.imgPreload=new Image;a.imgPreload.onload=
function(){this.onload=this.onerror=null;a.coming.width=this.width;a.coming.height=this.height;a._afterLoad()};a.imgPreload.onerror=function(){this.onload=this.onerror=null;a._error("image")};a.imgPreload.src=a.coming.href;a.imgPreload.width||a.showLoading()},_loadAjax:function(){a.showLoading();a.ajaxLoad=d.ajax(d.extend({},a.coming.ajax,{url:a.coming.href,error:function(b,c){"abort"!==c?a._error("ajax",b):a.hideLoading()},success:function(b,c){"success"===c&&(a.coming.content=b,a._afterLoad())}}))},
_preloadImages:function(){var b=a.group,c=a.current,e=b.length,f;if(c.preload&&!(2>b.length))for(var g=1;g<=Math.min(c.preload,e-1);g++)if(f=b[(c.index+g)%e],f=d(f).attr("href")||f)(new Image).src=f},_afterLoad:function(){a.hideLoading();a.coming&&!1!==a.trigger("afterLoad",a.current)?(a.isOpened?(d(".fancybox-item").remove(),a.wrap.stop(!0).removeClass("fancybox-opened"),a.inner.css("overflow","hidden"),a.transitions[a.current.prevMethod]()):(d(".fancybox-wrap").stop().trigger("onReset").remove(),
a.trigger("afterClose")),a.unbindEvents(),a.isOpen=!1,a.current=a.coming,a.wrap=d(a.current.tpl.wrap).addClass("fancybox-"+(t?"mobile":"desktop")+" fancybox-tmp "+a.current.wrapCSS).appendTo("body"),a.outer=d(".fancybox-outer",a.wrap).css("padding",a.current.padding+"px"),a.inner=d(".fancybox-inner",a.wrap),a._setContent()):a.coming=!1},_setContent:function(){var b,c,e=a.current,f=e.type;switch(f){case "inline":case "ajax":case "html":b=e.content;b instanceof d&&(b=b.show().detach(),b.parent().hasClass("fancybox-inner")&&
b.parents(".fancybox-wrap").trigger("onReset").remove(),d(a.wrap).bind("onReset",function(){b.appendTo("body").hide()}));e.autoSize&&(c=d('<div class="fancybox-tmp '+a.current.wrapCSS+'"></div>').appendTo("body").append(b),e.width=c.width(),e.height=c.height(),c.width(a.current.width),c.height()>e.height&&(c.width(e.width+1),e.width=c.width(),e.height=c.height()),b=c.contents().detach(),c.remove());break;case "image":b=e.tpl.image.replace("{href}",e.href);e.aspectRatio=!0;break;case "swf":b=e.tpl.swf.replace(/\{width\}/g,
e.width).replace(/\{height\}/g,e.height).replace(/\{href\}/g,e.href)}if("iframe"===f){b=d(e.tpl.iframe.replace("{rnd}",(new Date).getTime())).attr("scrolling",e.scrolling);e.scrolling="auto";if(e.autoSize){b.width(e.width);a.showLoading();b.data("ready",!1).appendTo(a.inner).bind({onCancel:function(){d(this).unbind();a._afterZoomOut()},load:function(){var b=d(this),c;try{this.contentWindow.document.location&&(c=b.contents().find("body").height()+12,b.height(c))}catch(f){e.autoSize=!1}!1===b.data("ready")?
(a.hideLoading(),c&&(a.current.height=c),a._beforeShow(),b.data("ready",!0)):c&&a.update()}}).attr("src",e.href);return}b.attr("src",e.href)}else if("image"===f||"swf"===f)e.autoSize=!1,e.scrolling="visible";a.inner.append(b);a._beforeShow()},_beforeShow:function(){a.coming=null;a.trigger("beforeShow");a._setDimension();a.wrap.hide().removeClass("fancybox-tmp");a.bindEvents();a._preloadImages();a.transitions[a.isOpened?a.current.nextMethod:a.current.openMethod]()},_setDimension:function(){var b=a.wrap,
c=a.outer,e=a.inner,f=a.current,g=a.getViewport(),q=f.margin,h=2*f.padding,l=f.width,m=f.height,k=f.maxWidth,n=f.maxHeight,p=f.minWidth,t=f.minHeight,r;g.w-=q[1]+q[3];g.h-=q[0]+q[2];-1<l.toString().indexOf("%")&&(l=(g.w-h)*parseFloat(l)/100);-1<m.toString().indexOf("%")&&(m=(g.h-h)*parseFloat(m)/100);q=l/m;l+=h;m+=h;f.fitToView&&(k=Math.min(g.w,k),n=Math.min(g.h,n));f.aspectRatio?(l>k&&(l=k,m=(l-h)/q+h),m>n&&(m=n,l=(m-h)*q+h),l<p&&(l=p,m=(l-h)/q+h),m<t&&(m=t,l=(m-h)*q+h)):(l=Math.max(p,Math.min(l,
k)),m=Math.max(t,Math.min(m,n)));l=Math.round(l);m=Math.round(m);d(b.add(c).add(e)).width("auto").height("auto");e.width(l-h).height(m-h);b.width(l);r=b.height();if(l>k||r>n)for(;(l>k||r>n)&&l>p&&r>t;)m-=10,f.aspectRatio?(l=Math.round((m-h)*q+h),l<p&&(l=p,m=(l-h)/q+h)):l-=10,e.width(l-h).height(m-h),b.width(l),r=b.height();f.dim={width:l,height:r};f.canGrow=f.autoSize&&m>t&&m<n;f.canShrink=!1;f.canExpand=!1;l-h<f.width||m-h<f.height?f.canExpand=!0:(l>g.w||r>g.h)&&l>p&&m>t&&(f.canShrink=!0);b=r-h;
a.innerSpace=b-e.height();a.outerSpace=b-c.height()},_getPosition:function(b){var c=a.current,d=a.getViewport(),f=c.margin,g=a.wrap.width()+f[1]+f[3],k=a.wrap.height()+f[0]+f[2],h={position:"absolute",top:f[0]+d.y,left:f[3]+d.x};c.fixed&&(!b||!1===b[0])&&k<=d.h&&g<=d.w&&(h={position:"fixed",top:f[0],left:f[3]});h.top=Math.ceil(Math.max(h.top,h.top+(d.h-k)*c.topRatio))+"px";h.left=Math.ceil(Math.max(h.left,h.left+.5*(d.w-g)))+"px";return h},_afterZoomIn:function(){var b=a.current,c=b.scrolling;a.isOpen=
a.isOpened=!0;a.wrap.addClass("fancybox-opened").css("overflow","visible");a.update();a.inner.css("overflow","yes"===c?"scroll":"no"===c?"hidden":c);(b.closeClick||b.nextClick)&&a.inner.css("cursor","pointer").bind("click.fb",b.nextClick?a.next:a.close);b.closeBtn&&d(b.tpl.closeBtn).appendTo(a.outer).bind("click.fb",a.close);b.arrows&&1<a.group.length&&((b.loop||0<b.index)&&d(b.tpl.prev).appendTo(a.inner).bind("click.fb",a.prev),(b.loop||b.index<a.group.length-1)&&d(b.tpl.next).appendTo(a.inner).bind("click.fb",
a.next));a.trigger("afterShow");a.opts.autoPlay&&!a.player.isActive&&(a.opts.autoPlay=!1,a.play())},_afterZoomOut:function(){a.trigger("afterClose");a.wrap.trigger("onReset").remove();d.extend(a,{group:{},opts:{},current:null,isActive:!1,isOpened:!1,isOpen:!1,wrap:null,outer:null,inner:null})}});a.transitions={getOrigPosition:function(){var b=a.current,c=b.element,e=b.padding,f=d(b.orig),g={},k=50,h=50;!f.length&&b.isDom&&d(c).is(":visible")&&(f=d(c).find("img:first"),f.length||(f=d(c)));f.length?
(g=f.offset(),f.is("img")&&(k=f.outerWidth(),h=f.outerHeight())):(b=a.getViewport(),g.top=b.y+.5*(b.h-h),g.left=b.x+.5*(b.w-k));return{top:Math.ceil(g.top-e)+"px",left:Math.ceil(g.left-e)+"px",width:Math.ceil(k+2*e)+"px",height:Math.ceil(h+2*e)+"px"}},step:function(b,c){var d,f,g;if("width"===c.prop||"height"===c.prop)f=g=Math.ceil(b-2*a.current.padding),"height"===c.prop&&(d=(b-c.start)/(c.end-c.start),c.start>c.end&&(d=1-d),f-=a.innerSpace*d,g-=a.outerSpace*d),a.inner[c.prop](f),a.outer[c.prop](g)},
zoomIn:function(){var b=a.wrap,c=a.current,e,f;e=c.dim;"elastic"===c.openEffect?(f=d.extend({},e,a._getPosition(!0)),delete f.position,e=this.getOrigPosition(),c.openOpacity&&(e.opacity=0,f.opacity=1),a.outer.add(a.inner).width("auto").height("auto"),b.css(e).show(),b.animate(f,{duration:c.openSpeed,easing:c.openEasing,step:this.step,complete:a._afterZoomIn})):(b.css(d.extend({},e,a._getPosition())),"fade"===c.openEffect?b.fadeIn(c.openSpeed,a._afterZoomIn):(b.show(),a._afterZoomIn()))},zoomOut:function(){var b=
a.wrap,c=a.current,d;"elastic"===c.closeEffect?("fixed"===b.css("position")&&b.css(a._getPosition(!0)),d=this.getOrigPosition(),c.closeOpacity&&(d.opacity=0),b.animate(d,{duration:c.closeSpeed,easing:c.closeEasing,step:this.step,complete:a._afterZoomOut})):b.fadeOut("fade"===c.closeEffect?c.closeSpeed:0,a._afterZoomOut)},changeIn:function(){var b=a.wrap,c=a.current,d;"elastic"===c.nextEffect?(d=a._getPosition(!0),d.opacity=0,d.top=parseInt(d.top,10)-200+"px",b.css(d).show().animate({opacity:1,top:"+=200px"},
{duration:c.nextSpeed,easing:c.nextEasing,complete:a._afterZoomIn})):(b.css(a._getPosition()),"fade"===c.nextEffect?b.hide().fadeIn(c.nextSpeed,a._afterZoomIn):(b.show(),a._afterZoomIn()))},changeOut:function(){var b=a.wrap,c=a.current,e=function(){d(this).trigger("onReset").remove()};b.removeClass("fancybox-opened");"elastic"===c.prevEffect?b.animate({opacity:0,top:"+=200px"},{duration:c.prevSpeed,easing:c.prevEasing,complete:e}):b.fadeOut("fade"===c.prevEffect?c.prevSpeed:0,e)}};a.helpers.overlay=
{overlay:null,update:function(){var a,c;this.overlay.width(0).height(0);d.browser.msie?(a=Math.max(k.documentElement.scrollWidth,k.body.scrollWidth),c=Math.max(k.documentElement.offsetWidth,k.body.offsetWidth),a=a<c?p.width():a):a=u.width();this.overlay.width(a).height(u.height())},beforeShow:function(b){this.overlay||(b=d.extend(!0,{speedIn:"fast",closeClick:!0,opacity:1,css:{background:"black"}},b),this.overlay=d('<div id="fancybox-overlay"></div>').css(b.css).appendTo("body"),this.update(),b.closeClick&&
this.overlay.bind("click.fb",a.close),p.bind("resize.fb",d.proxy(this.update,this)),this.overlay.fadeTo(b.speedIn,b.opacity))},onUpdate:function(){this.update()},afterClose:function(a){this.overlay&&this.overlay.fadeOut(a.speedOut||0,function(){d(this).remove()});this.overlay=null}};a.helpers.title={beforeShow:function(b){var c;if(c=a.current.title)c=d('<div class="fancybox-title fancybox-title-'+b.type+'-wrap">'+c+"</div>").appendTo("body"),"float"===b.type&&(c.width(c.width()),c.wrapInner('<span class="child"></span>'),
a.current.margin[2]+=Math.abs(parseInt(c.css("margin-bottom"),10))),c.appendTo("over"===b.type?a.inner:"outside"===b.type?a.wrap:a.outer)}};d.fn.fancybox=function(b){var c=d(this),e=this.selector||"",f,g=function(g){var h=this,k="rel",m=h[k],n=f;g.ctrlKey||g.altKey||g.shiftKey||g.metaKey||(g.preventDefault(),m||(k="data-fancybox-group",m=d(h).attr("data-fancybox-group")),m&&""!==m&&"nofollow"!==m&&(h=e.length?d(e):c,h=h.filter("["+k+'="'+m+'"]'),n=h.index(this)),b.index=n,a.open(h,b))};b=b||{};f=
b.index||0;e?u.undelegate(e,"click.fb-start").delegate(e,"click.fb-start",g):c.unbind("click.fb-start").bind("click.fb-start",g);return this}})(window,document,jQuery);
(function(r){var k=r.fancybox;k.helpers.buttons={tpl:'<div id="fancybox-buttons"><ul><li><a class="btnPrev" title="'+ulb.prev+'" href="javascript:;"></a></li><li><a class="btnPlay" title="'+ulb.btnPlay+'" href="javascript:;"></a></li><li><a class="btnNext" title="'+ulb.next+'" href="javascript:;"></a></li><li><a class="btnToggle" title="'+ulb.btnToggle+'" href="javascript:;"></a></li><li><a class="btnClose" title="'+ulb.closeBtn+'" href="javascript:jQuery.fancybox.close();"></a></li></ul></div>',
list:null,buttons:{},update:function(){var d=this.buttons.toggle.removeClass("btnDisabled btnToggleOn");k.current.canShrink?d.addClass("btnToggleOn"):k.current.canExpand||d.addClass("btnDisabled")},beforeLoad:function(d){1>k.group.length?(k.coming.helpers.buttons=!1,k.coming.closeBtn=!0):k.coming.margin["bottom"===d.position?2:0]+=30},onPlayStart:function(){this.list&&this.buttons.play.attr("title","Pause slideshow").addClass("btnPlayOn")},onPlayEnd:function(){this.list&&this.buttons.play.attr("title",
"Start slideshow").removeClass("btnPlayOn")},afterShow:function(d){this.list||(this.list=r(d.tpl||this.tpl).addClass(d.position||"top").appendTo("body"),this.buttons={prev:this.list.find(".btnPrev").click(k.prev),next:this.list.find(".btnNext").click(k.next),play:this.list.find(".btnPlay").click(k.play),toggle:this.list.find(".btnToggle").click(k.toggle)});d=this.buttons;0<k.current.index||k.current.loop?d.prev.removeClass("btnDisabled"):d.prev.addClass("btnDisabled");k.current.loop||k.current.index<
k.group.length-1?(d.next.removeClass("btnDisabled"),d.play.removeClass("btnDisabled")):(d.next.addClass("btnDisabled"),d.play.addClass("btnDisabled"));this.update()},onUpdate:function(){this.update()},beforeClose:function(){this.list&&this.list.remove();this.list=null;this.buttons={}}}})(jQuery);var fixedFlag=!0,openEf="elastic";$.browser.msie&&10>$.browser.version&&"BackCompat"==document.compatMode&&(fixedFlag=!1,openEf="fade");
$(document).ready(function(){$(".ulightbox").fancybox({padding:3,preload:5,openEffect:openEf,closeEffect:"elastic",nextEffect:"fade",prevEffect:"fade",openEasing:"linear",nextEasing:"linear",prevEasing:"linear",fixed:fixedFlag,helpers:{title:null,overlay:{opacity:.1,speedIn:0,speedOut:0},buttons:{}}});$(".uphoto .ulightbox").fancybox({padding:3,preload:5,openEffect:openEf,closeEffect:"elastic",nextEffect:"fade",prevEffect:"fade",openEasing:"linear",nextEasing:"linear",prevEasing:"linear",fixed:fixedFlag,
beforeShow:function(){var r=$(this.element).data("url");r&&(this.title='<a class="ulb-photopage-link" href="'+r+'">'+ulb.photoPage+"</a>");var k=$(this.element).attr("data-title"),d=$(this.element).attr("data-alt");setTimeout(function(){k&&$(".fancybox-image").attr("title",k);d&&$(".fancybox-image").attr("alt",d)},0)},helpers:{title:{type:"float"},overlay:{opacity:.1,speedIn:0,speedOut:0},buttons:{}}});$(window).scroll(function(){$.browser.msie&&10>$.browser.version&&"BackCompat"==document.compatMode&&
$.fancybox.reposition()})});function _bldCont1(r,k){for(var d="allEntImgs"+r,p=[],u=0,a=window[d].length;u<a;u++)p.push({href:window[d][u][0]});$.fancybox(p,{index:k,padding:3,preload:5,openEffect:openEf,closeEffect:"elastic",nextEffect:"fade",prevEffect:"fade",openEasing:"linear",nextEasing:"linear",prevEasing:"linear",fixed:fixedFlag,helpers:{title:null,overlay:{opacity:.1,speedIn:0,speedOut:0},buttons:{}}})}
function videoLightbox(){$.browser.msie&&10>$.browser.version&&"BackCompat"==document.compatMode&&$("#videocontent").width($("#videocontent_obj").children().width());$("#videocontent").width($(".vep-videocontent").children().width());$.browser.opera&&($(".vep-videocontent").width($(".vep-videocontent").children().width()),$(".vep-videocontent").height($(".vep-videocontent").children().height()));$.fancybox({href:"#videocontent",fitToView:!1,width:"70%",height:"70%",autoSize:!0,closeClick:!1,openEffect:"none",
closeEffect:"none",padding:3,fixed:fixedFlag,afterClose:function(){setTimeout($(".vep-videocontent").html(""),100)},helpers:{title:null,overlay:{opacity:.8,speedIn:0,speedOut:0},buttons:{}}})};
